-- 0010_task_channels.sql
--
-- Adds a workspace messaging subsystem alongside the Task hierarchy:
--
--   Workspace -> Channel -> Message -> [Reply]
--
-- Purely additive. No existing table is altered and no existing row is touched. Nothing here
-- creates a Channel: the tables ship empty and the first Channel in any workspace is created
-- through the API by a manager. In particular this migration does NOT create "Lounge" or
-- "Showtime Pools Main" anywhere.
--
-- SAME COMPOSITE-TENANT-SAFETY IDIOM AS 0006/0009:
-- every child table carries workspace_id redundantly and every parent reference is a COMPOSITE
-- foreign key that includes it. A cross-workspace reference therefore has no row for the FK to
-- resolve against and is rejected by the database before it can commit — it is structurally
-- impossible rather than prevented by an application check a future caller could forget. This
-- is what makes "no cross-workspace replies" a schema guarantee: task_channel_messages'
-- parent reference targets (workspace_id, channel_id, id), so a reply can only ever attach to
-- a message in the SAME channel of the SAME workspace.
--
-- task_channels exposes two unique keys for two different composite-FK purposes, matching the
-- multi-key pattern task_items and task_folders already use:
--   task_channels_tenant_key  (workspace_id, id)  -- generic composite-FK target
-- and task_channel_messages exposes:
--   task_channel_messages_channel_key (workspace_id, channel_id, id)
--     -- the SAME-CHANNEL-enforcing target used by the reply edge.

-- ── Channels ──────────────────────────────────────────────────────────────────────────
--
-- space_id is OPTIONAL and deliberately nullable. Channels are a WORKSPACE-level surface
-- (they sit below Spaces in the navigation, not inside one), so the ordinary case is NULL.
-- The column exists so a Channel can later be associated with a Space without a second
-- migration. It is metadata only: no access-control decision anywhere reads space_id, so
-- associating a Channel with a Space can never widen or narrow who can see it. Membership is
-- workspace-scoped, exactly as it is for every other task_* table.
create table if not exists public.task_channels (
  id            uuid primary key default gen_random_uuid(),
  workspace_id  text not null references public.workspaces(id) on delete cascade,
  space_id      uuid,
  name          text not null check (length(trim(name)) between 1 and 80),
  -- Normalised, lowercase, URL-safe. Generated by the API, never accepted from a client.
  slug          text not null check (slug ~ '^[a-z0-9][a-z0-9-]{0,79}$'),
  description   text check (description is null or length(description) <= 2000),
  -- 'workspace'  = every active member of the workspace may read and (by role) post.
  -- 'restricted' = only actors with a row in task_channel_members may read or post.
  visibility    text not null default 'workspace'
                  check (visibility in ('workspace', 'restricted')),
  position      numeric not null default 1000,
  version       integer not null default 1 check (version > 0),
  archived_at   timestamptz,
  created_by    uuid,
  updated_by    uuid,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  constraint task_channels_tenant_key unique (workspace_id, id),
  constraint task_channels_space_fk foreign key (workspace_id, space_id)
    references public.task_spaces (workspace_id, id) on delete set null,
  constraint task_channels_created_by_fk foreign key (workspace_id, created_by)
    references public.task_workspace_actors (workspace_id, id),
  constraint task_channels_updated_by_fk foreign key (workspace_id, updated_by)
    references public.task_workspace_actors (workspace_id, id)
);

-- Slug uniqueness among LIVE channels within a workspace (mirrors task_spaces_unique_live_name).
-- Archived channels are excluded so a name can be reused after archiving.
create unique index if not exists task_channels_unique_live_slug
  on public.task_channels (workspace_id, slug) where archived_at is null;

create index if not exists task_channels_ws_position_idx
  on public.task_channels (workspace_id, position) where archived_at is null;
create index if not exists task_channels_ws_archived_idx
  on public.task_channels (workspace_id, archived_at);

-- ── Channel membership ────────────────────────────────────────────────────────────────
--
-- Only consulted for visibility = 'restricted'. Rows may exist for a 'workspace' channel
-- (e.g. a channel that was restricted and later opened up); they are simply not the access
-- test in that mode.
create table if not exists public.task_channel_members (
  id            uuid primary key default gen_random_uuid(),
  workspace_id  text not null references public.workspaces(id) on delete cascade,
  channel_id    uuid not null,
  actor_id      uuid not null,
  -- 'moderator' is scoped to this channel and is ADDITIVE to the global role. It never grants
  -- anything a workspace manager does not already have, and never overrides READ_ONLY: a
  -- read-only member of a channel remains read-only.
  role          text not null default 'member' check (role in ('member', 'moderator')),
  added_by      uuid,
  created_at    timestamptz not null default now(),

  constraint task_channel_members_unique unique (workspace_id, channel_id, actor_id),
  constraint task_channel_members_channel_fk foreign key (workspace_id, channel_id)
    references public.task_channels (workspace_id, id) on delete cascade,
  constraint task_channel_members_actor_fk foreign key (workspace_id, actor_id)
    references public.task_workspace_actors (workspace_id, id) on delete cascade,
  constraint task_channel_members_added_by_fk foreign key (workspace_id, added_by)
    references public.task_workspace_actors (workspace_id, id)
);

create index if not exists task_channel_members_ws_actor_idx
  on public.task_channel_members (workspace_id, actor_id);
create index if not exists task_channel_members_ws_channel_idx
  on public.task_channel_members (workspace_id, channel_id);

-- ── Messages ──────────────────────────────────────────────────────────────────────────
--
-- body is PLAIN TEXT. Nothing in this system stores, accepts or emits HTML; the API
-- sanitises on the way in (control and bidi characters removed, length bounded) and returns
-- the text verbatim in a JSON payload. Any renderer must escape it — React does so by default.
--
-- created_at is the cursor's high-order component and is SERVER-GENERATED (default now()).
-- The API never accepts a client timestamp, so a client cannot place a message out of order,
-- backdate one, or skip another reader's cursor.
create table if not exists public.task_channel_messages (
  id                uuid primary key default gen_random_uuid(),
  workspace_id      text not null references public.workspaces(id) on delete cascade,
  channel_id        uuid not null,
  -- Always the SERVER-resolved actor. Never read from the request body.
  author_actor_id   uuid not null,
  body              text not null check (length(body) between 1 and 4000),
  parent_message_id uuid,
  -- Client-supplied idempotency token. Unique per author within a channel, so a retried send
  -- returns the original message instead of creating a second one.
  client_token      text check (client_token is null or length(client_token) between 8 and 100),
  edited_at         timestamptz,
  -- Soft delete only. Nothing in this module ever hard-deletes a message.
  deleted_at        timestamptz,
  deleted_by        uuid,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),

  constraint task_channel_messages_channel_key unique (workspace_id, channel_id, id),
  constraint task_channel_messages_channel_fk foreign key (workspace_id, channel_id)
    references public.task_channels (workspace_id, id) on delete cascade,
  -- The reply edge. Targeting (workspace_id, channel_id, id) is what makes a cross-channel OR
  -- cross-workspace reply impossible at the database layer.
  constraint task_channel_messages_parent_fk
    foreign key (workspace_id, channel_id, parent_message_id)
    references public.task_channel_messages (workspace_id, channel_id, id) on delete set null,
  constraint task_channel_messages_author_fk foreign key (workspace_id, author_actor_id)
    references public.task_workspace_actors (workspace_id, id),
  constraint task_channel_messages_deleted_by_fk foreign key (workspace_id, deleted_by)
    references public.task_workspace_actors (workspace_id, id)
);

-- Idempotency. Partial (client_token is not null) so tokenless sends are unconstrained.
create unique index if not exists task_channel_messages_client_token_unique
  on public.task_channel_messages (workspace_id, channel_id, author_actor_id, client_token)
  where client_token is not null;

-- The keyset-pagination index: (created_at, id) is the cursor's total order, so both history
-- paging and after-cursor polling are index-only range scans within one channel.
create index if not exists task_channel_messages_channel_cursor_idx
  on public.task_channel_messages (workspace_id, channel_id, created_at, id);

-- Unread counting: "messages in this channel created after my last-read timestamp".
create index if not exists task_channel_messages_unread_idx
  on public.task_channel_messages (workspace_id, channel_id, created_at)
  where deleted_at is null;

create index if not exists task_channel_messages_thread_idx
  on public.task_channel_messages (workspace_id, channel_id, parent_message_id)
  where parent_message_id is not null;

-- Rate-limit backstop: counts one author's recent sends independently of which serverless
-- instance served them.
create index if not exists task_channel_messages_author_recent_idx
  on public.task_channel_messages (workspace_id, author_actor_id, created_at);

-- ── Read cursors ──────────────────────────────────────────────────────────────────────
--
-- One row per (channel, actor). last_read_at is the authoritative cursor for unread counts;
-- last_read_message_id is kept alongside it for "jump to where I left off" and is allowed to
-- dangle logically (it is only ever set to a message the caller could read at the time).
create table if not exists public.task_channel_reads (
  workspace_id         text not null references public.workspaces(id) on delete cascade,
  channel_id           uuid not null,
  actor_id             uuid not null,
  last_read_at         timestamptz not null default now(),
  last_read_message_id uuid,
  updated_at           timestamptz not null default now(),

  constraint task_channel_reads_pkey primary key (workspace_id, channel_id, actor_id),
  constraint task_channel_reads_channel_fk foreign key (workspace_id, channel_id)
    references public.task_channels (workspace_id, id) on delete cascade,
  constraint task_channel_reads_actor_fk foreign key (workspace_id, actor_id)
    references public.task_workspace_actors (workspace_id, id) on delete cascade
);

create index if not exists task_channel_reads_ws_actor_idx
  on public.task_channel_reads (workspace_id, actor_id);

-- ── Activity feed: widen entity_type to include 'channel' and 'channel_message' ───────────
-- The ONE non-purely-additive change in this migration, and it only WIDENS a CHECK: every
-- value that was accepted before is still accepted. No existing row's entity_type changes and
-- nothing that validated before can fail now. Guarded so re-running is a no-op, and written to
-- pick up 0009's widened list rather than assuming the original 0006 one.
do $$
begin
  if exists (
    select 1 from pg_constraint
    where conname = 'task_activity_events_entity_type_check'
      and conrelid = 'public.task_activity_events'::regclass
  ) then
    alter table public.task_activity_events
      drop constraint task_activity_events_entity_type_check;
    alter table public.task_activity_events
      add constraint task_activity_events_entity_type_check
      check (entity_type in
        ('space', 'list', 'status', 'task', 'assignment', 'time_entry', 'folder',
         'channel', 'channel_message'));
  end if;
end $$;

-- ── RLS and table privileges ──────────────────────────────────────────────────────────
-- Identical posture to every other task_* table (0008/0009): RLS enabled with ZERO policies is
-- deny-all for anon and authenticated, but that alone does not grant service_role access —
-- table privileges are a separate mechanism. Without the explicit grants below, service_role
-- would ALSO be refused (no privilege to bypass RLS against), silently breaking every Channel
-- route. anon/authenticated are revoked explicitly, INCLUDING the privileges Supabase grants
-- by default, which is why migration 0003 had to exist for the original task tables.
--
-- This posture is also precisely why Supabase Realtime is NOT used for these tables: Realtime
-- authorises a subscription as anon/authenticated against RLS policies, so streaming messages
-- to the browser would require both shipping a Supabase key to the client and adding SELECT
-- policies for authenticated — weakening deny-all. The API uses cursor polling instead.
do $$
declare t text;
begin
  foreach t in array array[
    'task_channels', 'task_channel_members', 'task_channel_messages', 'task_channel_reads'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on table public.%I from public', t);
    execute format('revoke all on table public.%I from anon', t);
    execute format('revoke all on table public.%I from authenticated', t);
    execute format('grant select, insert, update, delete on table public.%I to service_role', t);
    execute format('grant all on table public.%I to postgres', t);
  end loop;
end $$;
